// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for classifying revenue entries as 'retail' or 'wholesale' based on keywords.
 *
 * The flow takes a revenue report entry as input and returns a classification result ('retail' or 'wholesale').
 * @file
 * - classifyRevenue - The function to classify revenue entries.
 * - ClassifyRevenueInput - The input type for the classifyRevenue function.
 * - ClassifyRevenueOutput - The output type for the classifyRevenue function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ClassifyRevenueInputSchema = z.object({
  revenueEntry: z.string().describe('The revenue entry to classify.'),
  keywordsRetail: z.string().describe('Keywords indicating retail revenue, comma separated.'),
  keywordsWholesale: z.string().describe('Keywords indicating wholesale revenue, comma separated.'),
});
export type ClassifyRevenueInput = z.infer<typeof ClassifyRevenueInputSchema>;

const ClassifyRevenueOutputSchema = z.object({
  classification: z.enum(['retail', 'wholesale']).describe('The classification of the revenue entry.'),
});
export type ClassifyRevenueOutput = z.infer<typeof ClassifyRevenueOutputSchema>;

export async function classifyRevenue(input: ClassifyRevenueInput): Promise<ClassifyRevenueOutput> {
  return classifyRevenueFlow(input);
}

// Add the multiLanguageRule constant here
const multiLanguageRule = `CRITICAL: The provided revenue entry may contain descriptions and labels in English, Georgian (ქართული), and Russian (Русский). You MUST analyze the text in its original language without translating it. Understand the context and use the original language terms for classification.`;


const classifyRevenuePrompt = ai.definePrompt({
  name: 'classifyRevenuePrompt',
  input: {schema: ClassifyRevenueInputSchema},
  output: {schema: ClassifyRevenueOutputSchema},
  prompt: `${multiLanguageRule}

You are a revenue classification expert.
Given the following revenue entry, classify it as either 'retail' or 'wholesale'.
Consider the following keywords:
Retail Keywords: {{{keywordsRetail}}}
Wholesale Keywords: {{{keywordsWholesale}}}

Revenue Entry: {{{revenueEntry}}}

Classification:`, // Ensure the output is strictly 'retail' or 'wholesale'
  config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const classifyRevenueFlow = ai.defineFlow(
  {
    name: 'classifyRevenueFlow',
    inputSchema: ClassifyRevenueInputSchema,
    outputSchema: ClassifyRevenueOutputSchema,
  },
  async input => {
    const {output} = await classifyRevenuePrompt(input);
    return output!;
  }
);
